name: Integration Test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            artifact-name: Windows x86-64
            architecture: x64
            test-type: Analysis
          - os: macos-latest
            artifact-name: macOS x86-64
            architecture: x64
            test-type: Analysis
          - os: ubuntu-latest
            artifact-name: Linux x86-64
            architecture: x64
            test-type: Analysis
          - os: windows-2019
            artifact-name: Windows x86-64
            architecture: x64
            test-type: Generation
          - os: macos-latest
            artifact-name: macOS x86-64
            architecture: x64
            test-type: Generation
          - os: ubuntu-latest
            artifact-name: Linux x86-64
            architecture: x64
            test-type: Generation

    name: "${{ matrix.test-type }} - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: ${{ matrix.architecture }}

      - name: Install RoboRIO Toolchain
        run: ./gradlew installRoborioToolchain

      - name: Run Integration Tests
        run: ./gradlew run${{ matrix.test-type }}IntegrationTests -PwithIntegration

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: Upload Bad Json
          path: jsons/
          if-no-files-found: ignore
